jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'

    - name: Build and Test
      run: |
        npm install
        npm run build --if-present
        npm run start --if-present
        npm run test
        npm run test:e2e
        npm run test:cov

    - name: Build Docker Image
      run: docker build -t nodejs:v1

    -name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
     
    uses: mr-smithers-excellent/docker-build-push@v6
    with:
      image: image-name
      registry: ${{ECR_REPOSITORY}}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
